/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tours/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Extract a draft tour from a photographed plan (vision) and geocode it.
         *
         *     Runs Claude vision extraction, persists a draft tour + stops (status
         *     ``draft``/``unconfirmed``) preserving row order, geocodes each stop
         *     best-effort (cached Nominatim), and returns the draft for the Confirm
         *     screen. Runs in a threadpool (sync def), so the multi-second model call
         *     doesn't block the event loop.
         */
        post: operations["extract_tours_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tour */
        get: operations["get_tour_tours__tour_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Tour
         * @description Change per-tour settings (currently date_mode). Switching date_mode
         *     does not reschedule by itself — the client re-runs optimise after.
         */
        patch: operations["update_tour_tours__tour_id__patch"];
        trace?: never;
    };
    "/tours/{tour_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft
         * @description The current draft (pre-commit) tour, for a reloaded/deep-linked Confirm.
         */
        get: operations["get_draft_tours__tour_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/draft/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Draft Stop
         * @description Apply the user's corrections to one draft stop.
         *
         *     Only explicitly-set fields change. Editing a field clears its
         *     low-confidence flag; changing any address field re-geocodes the stop so the
         *     map stays correct after corrections.
         */
        patch: operations["patch_draft_stop_tours__tour_id__draft_stops__stop_id__patch"];
        trace?: never;
    };
    "/tours/{tour_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stops
         * @description Committed stops with address, task labels, and geocoded coordinate.
         *
         *     Returns every stop of the tour (including ungeocoded/unassigned ones, whose
         *     lat/lng are null) in the tour plan's original row order. Powers the mobile
         *     Review (edit hours) and Map (markers + detail) screens.
         */
        get: operations["list_stops_tours__tour_id__stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Tour
         * @description Confirm a tour and best-effort enrich stop opening hours from OSM.
         *
         *     Geocoding is assumed to have run already (stops carry a geom). Only stops
         *     whose hours are still unknown (hours_source='default') are looked up, so
         *     manual and previously-fetched OSM hours are never overwritten.
         */
        post: operations["commit_tour_tours__tour_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimise
         * @description Assign every open market to a working day and order it.
         *
         *     scope='remaining' re-plans mid-week: days before from_date (default
         *     today) and every completed stop stay untouched; the still-open stops —
         *     including any stranded on earlier days — spread over the remaining days,
         *     starting from the last completed stop.
         */
        post: operations["optimise_tours__tour_id__optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description The stored schedule, without re-solving — what the map should load.
         *
         *     Re-optimising on read would overwrite manual edits and mid-week state,
         *     so this endpoint only mirrors the database. Drive time and day-end are
         *     solver outputs and read as zero/empty here.
         */
        get: operations["get_plan_tours__tour_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_stops__stop_id__patch"];
        trace?: never;
    };
    "/stops/{stop_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Stop Plan
         * @description Manually move a stop to another day (or off the plan entirely).
         *
         *     The edit is authoritative: it survives map reloads because clients read
         *     GET /tours/{id}/plan, which never re-solves. Both affected days are
         *     re-sequenced; the moved stop's ETA clears until the next optimise run.
         */
        patch: operations["update_stop_plan_stops__stop_id__plan_patch"];
        trace?: never;
    };
    "/stops/{stop_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Stop
         * @description Mark a stop done. Idempotent: a repeat call (e.g. an offline-sync
         *     retry) keeps the original completed_at unless force is set.
         */
        post: operations["complete_stop_stops__stop_id__complete_post"];
        /**
         * Uncomplete Stop
         * @description Undo a mis-tapped completion: clear completed_at. Idempotent.
         */
        delete: operations["uncomplete_stop_stops__stop_id__complete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stores
         * @description The store catalog, A-Z, for the office view. needs_attributes=true
         *     filters to stores still missing a crowdsourced attribute (the "which
         *     facts are we lacking" list); false filters to complete ones.
         */
        get: operations["list_stores_stores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/service-times/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Store Service Times
         * @description Re-learn every store's service duration from completion history (P4).
         *
         *     Recomputes from scratch on each call — history is small — and needs OSRM
         *     for the drive legs between completed stops. Triggered from the office's
         *     stores page; new tours pick the learned values up at extraction time.
         */
        post: operations["recompute_store_service_times_stores_service_times_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_stores__store_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Store Visits
         * @description Every stop ever linked to this store, newest first — the office's
         *     visit history with predicted ETA vs. actual completion.
         */
        get: operations["store_visits_stores__store_id__visits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Store Feedback
         * @description The store's full visit-feedback history, newest first (mobile detail
         *     view + dashboard). Feedback is append-only — no edit/delete anywhere; a
         *     wrong store *fact* is fixed via PATCH /stores/{id}/attributes instead.
         */
        get: operations["store_feedback_stores__store_id__feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Store Attributes */
        patch: operations["update_store_attributes_stores__store_id__attributes_patch"];
        trace?: never;
    };
    "/feedback/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Feedback Photo
         * @description Store a feedback photo; the returned photo_path goes into POST
         *     /feedback. Uploaded separately so the feedback body itself stays a small
         *     JSON document the offline outbox can park and replay.
         */
        post: operations["upload_feedback_photo_feedback_photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feedback
         * @description List feedback, newest first, optionally filtered. Feedback is
         *     append-only: there are deliberately no update/delete endpoints.
         */
        get: operations["list_feedback_feedback_get"];
        put?: never;
        /**
         * Create Feedback
         * @description Record after-visit feedback. Idempotent on client_uuid: an offline-sync
         *     retry of an already-stored POST returns the existing row (200, not 201).
         */
        post: operations["create_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_tours_extract_post */
        Body_extract_tours_extract_post: {
            /** Image */
            image: string;
        };
        /** Body_upload_feedback_photo_feedback_photos_post */
        Body_upload_feedback_photo_feedback_photos_post: {
            /** Image */
            image: string;
        };
        /** CommitResult */
        CommitResult: {
            /** Tour Id */
            tour_id: number;
            /** Status */
            status: string;
            /** Stops Total */
            stops_total: number;
            /** Stops Enriched */
            stops_enriched: number;
        };
        /**
         * DateMode
         * @description Whether stop dates from the plan are binding or a starting point.
         *
         *     fixed: stops stay pinned to their printed plan date (Datum governs; the
         *     optimiser only sequences within each day). optimized: the optimiser may
         *     move stops between days.
         * @enum {string}
         */
        DateMode: "fixed" | "optimized";
        /** DayStop */
        DayStop: {
            /** Stop Id */
            stop_id: number;
            /** Sequence */
            sequence: number;
            /** Eta */
            eta: string | null;
        };
        /** DaySummary */
        DaySummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Stops */
            stops: components["schemas"]["DayStop"][];
            /** Drive Seconds */
            drive_seconds: number;
            /** Service Seconds */
            service_seconds: number;
            /** Day End */
            day_end: string | null;
            /** Near Limit */
            near_limit: boolean;
        };
        /** DraftStop */
        DraftStop: {
            /** Id */
            id: number;
            /** Street */
            street: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** City */
            city: string | null;
            /** Order No */
            order_no: string | null;
            /** Tasks */
            tasks: string | null;
            /** Remarks */
            remarks: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            /** Confidence */
            confidence: {
                [key: string]: number;
            };
        };
        /**
         * DraftStopUpdate
         * @description PATCH body for a draft stop — only explicitly-set fields are applied.
         *
         *     A field sent as ``null`` clears it; the endpoint distinguishes that from an
         *     omitted field via ``model_fields_set``.
         */
        DraftStopUpdate: {
            /** Street */
            street?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /** Order No */
            order_no?: string | null;
            /** Tasks */
            tasks?: string | null;
            /** Service Minutes */
            service_minutes?: number | null;
        };
        /**
         * FeedbackCreate
         * @description One piece of after-visit feedback. store_id/tour_id are derived from
         *     the stop server-side so the row can't contradict itself. client_uuid is
         *     the client-generated idempotency key: offline sync may retry the same
         *     POST, which must return the existing row instead of creating another.
         */
        FeedbackCreate: {
            /** Stop Id */
            stop_id: number;
            /** Client Uuid */
            client_uuid: string;
            /** Employee */
            employee?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["FeedbackTag"][];
            /** Note */
            note?: string | null;
            /** Photo Path */
            photo_path?: string | null;
        };
        /** FeedbackRead */
        FeedbackRead: {
            /** Id */
            id: number;
            /** Store Id */
            store_id: number | null;
            /** Tour Id */
            tour_id: number | null;
            /** Stop Id */
            stop_id: number | null;
            /** Employee */
            employee: string | null;
            /** Tags */
            tags: string[];
            /** Note */
            note: string | null;
            /** Photo Path */
            photo_path: string | null;
            /** Client Uuid */
            client_uuid: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackTag
         * @description Controlled vocabulary for visit feedback tags.
         * @enum {string}
         */
        FeedbackTag: "parking_full" | "access_problem" | "took_longer" | "store_condition" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoursSource
         * @description Where a stop's opening/closing hours came from.
         * @enum {string}
         */
        HoursSource: "osm" | "manual" | "default";
        /**
         * OptimiseRequest
         * @description Optional POST /tours/{id}/optimise body.
         *
         *     scope='remaining' is the mid-week re-plan: completed stops stay where
         *     they are, everything still open (including stops stranded on earlier
         *     days) is redistributed over the days from from_date on. from_date
         *     defaults to today.
         */
        OptimiseRequest: {
            /**
             * Scope
             * @default week
             * @enum {string}
             */
            scope: "week" | "remaining";
            /** From Date */
            from_date?: string | null;
        };
        /** OptimiseResult */
        OptimiseResult: {
            /** Tour Id */
            tour_id: number;
            date_mode: components["schemas"]["DateMode"];
            /** Days */
            days: components["schemas"]["DaySummary"][];
            /** Unassigned */
            unassigned: components["schemas"]["UnassignedStop"][];
        };
        /**
         * PhotoUploadResult
         * @description Where an uploaded feedback photo landed; served under /media.
         */
        PhotoUploadResult: {
            /** Photo Path */
            photo_path: string;
        };
        /**
         * StopCompleteRequest
         * @description Body for POST /stops/{id}/complete. force re-stamps completed_at even
         *     when the stop was already completed (normally a repeat call is a no-op).
         */
        StopCompleteRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * StopDetail
         * @description A committed stop with the address, task labels, and coordinate the map
         *     needs. lat/lng come from the PostGIS geom (null until geocoded); tasks is
         *     the stop's task labels joined for display.
         */
        StopDetail: {
            /** Id */
            id: number;
            /** Tour Id */
            tour_id: number;
            /** Customer */
            customer: string | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            hours_source: components["schemas"]["HoursSource"];
            /** Status */
            status: string;
            /** Completed At */
            completed_at: string | null;
            /** Assigned Day */
            assigned_day?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Unassigned Reason */
            unassigned_reason?: string | null;
            /** Street */
            street: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** City */
            city: string | null;
            /** Tasks */
            tasks: string | null;
            /** Remarks */
            remarks: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Store Id */
            store_id: number | null;
            /** Store Attributes Complete */
            store_attributes_complete: boolean | null;
            /** Store Feedback Count */
            store_feedback_count: number;
        };
        /**
         * StopPlanUpdate
         * @description Manual plan edit (PATCH /stops/{id}/plan): move the stop to a day —
         *     appended, or at the 1-based position — or take it off the plan entirely
         *     (assigned_day=null).
         */
        StopPlanUpdate: {
            /** Assigned Day */
            assigned_day: string | null;
            /** Position */
            position?: number | null;
        };
        /** StopRead */
        StopRead: {
            /** Id */
            id: number;
            /** Tour Id */
            tour_id: number;
            /** Customer */
            customer: string | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            hours_source: components["schemas"]["HoursSource"];
            /** Status */
            status: string;
            /** Completed At */
            completed_at: string | null;
            /** Assigned Day */
            assigned_day?: string | null;
            /** Sequence */
            sequence?: number | null;
            /** Unassigned Reason */
            unassigned_reason?: string | null;
        };
        /**
         * StopUpdate
         * @description Per-stop manual overrides. Only provided fields are applied (PATCH).
         */
        StopUpdate: {
            /** Opening Time */
            opening_time?: string | null;
            /** Closing Time */
            closing_time?: string | null;
            /** Service Minutes */
            service_minutes?: number | null;
        };
        /**
         * StoreAttributesUpdate
         * @description Crowdsourced attribute capture. Only provided fields are applied
         *     (PATCH); an explicit null clears an attribute back to "not captured".
         */
        StoreAttributesUpdate: {
            size?: components["schemas"]["StoreSize"] | null;
            /** In Mall */
            in_mall?: boolean | null;
            /** Has Parking */
            has_parking?: boolean | null;
            /** Updated By */
            updated_by?: string | null;
        };
        /** StoreRead */
        StoreRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Street */
            street: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** City */
            city: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Default Tasks */
            default_tasks: string[] | null;
            /** Default Service Minutes */
            default_service_minutes: number | null;
            /** Learned Service Minutes */
            learned_service_minutes: number | null;
            /** Service Time Samples */
            service_time_samples: number;
            /** Service Times Updated At */
            service_times_updated_at: string | null;
            size: components["schemas"]["StoreSize"] | null;
            /** In Mall */
            in_mall: boolean | null;
            /** Has Parking */
            has_parking: boolean | null;
            /** Attributes Updated At */
            attributes_updated_at: string | null;
            /** Attributes Updated By */
            attributes_updated_by: string | null;
            /** Attributes Complete */
            attributes_complete: boolean;
        };
        /**
         * StoreServiceTimeRead
         * @description Per-store outcome of a service-time recompute run.
         */
        StoreServiceTimeRead: {
            /** Store Id */
            store_id: number;
            /** Name */
            name: string;
            /** Samples */
            samples: number;
            /** Learned Service Minutes */
            learned_service_minutes: number | null;
        };
        /**
         * StoreSize
         * @enum {string}
         */
        StoreSize: "small" | "medium" | "large";
        /**
         * StoreVisit
         * @description One (planned or completed) stop at this store, for the office view's
         *     visit-history table. eta is the optimiser's prediction, completed_at the
         *     crew's actual — the office watches the delta between them.
         */
        StoreVisit: {
            /** Stop Id */
            stop_id: number;
            /** Tour Id */
            tour_id: number;
            /** Calendar Week */
            calendar_week: number;
            /** Date */
            date: string | null;
            /** Employee */
            employee: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            /** Eta */
            eta: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** TourDraft */
        TourDraft: {
            /** Tour Id */
            tour_id: number;
            /** Stops */
            stops: components["schemas"]["DraftStop"][];
        };
        /** TourRead */
        TourRead: {
            /** Id */
            id: number;
            /** Customer */
            customer: string;
            /** Calendar Week */
            calendar_week: number;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Status */
            status: string;
            date_mode: components["schemas"]["DateMode"];
        };
        /**
         * TourUpdate
         * @description Per-tour settings. Only provided fields are applied (PATCH).
         */
        TourUpdate: {
            date_mode?: components["schemas"]["DateMode"] | null;
        };
        /** UnassignedStop */
        UnassignedStop: {
            /** Stop Id */
            stop_id: number;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_tours_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_tours_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tour_tours__tour_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tour_tours__tour_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TourUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_tours__tour_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_draft_stop_tours__tour_id__draft_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftStopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftStop"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_tours__tour_id__stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_tour_tours__tour_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimise_tours__tour_id__optimise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OptimiseRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_tours__tour_id__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_plan_stops__stop_id__plan_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopPlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_stop_stops__stop_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StopCompleteRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uncomplete_stop_stops__stop_id__complete_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stores_stores_get: {
        parameters: {
            query?: {
                needs_attributes?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_store_service_times_stores_service_times_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreServiceTimeRead"][];
                };
            };
        };
    };
    get_store_stores__store_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_visits_stores__store_id__visits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreVisit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_feedback_stores__store_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_store_attributes_stores__store_id__attributes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreAttributesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_feedback_photo_feedback_photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_feedback_photo_feedback_photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_feedback_get: {
        parameters: {
            query?: {
                store_id?: number | null;
                tour_id?: number | null;
                stop_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
