/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tours/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Extract a draft tour from a photographed plan (vision) and geocode it.
         *
         *     Runs Claude vision extraction, persists a draft tour + stops (status
         *     ``draft``/``unconfirmed``) preserving row order, geocodes each stop
         *     best-effort (cached Nominatim), and returns the draft for the Confirm
         *     screen. Runs in a threadpool (sync def), so the multi-second model call
         *     doesn't block the event loop.
         */
        post: operations["extract_tours_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft
         * @description The current draft (pre-commit) tour, for a reloaded/deep-linked Confirm.
         */
        get: operations["get_draft_tours__tour_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/draft/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Draft Stop
         * @description Apply the user's corrections to one draft stop.
         *
         *     Only explicitly-set fields change. Editing a field clears its
         *     low-confidence flag; changing any address field re-geocodes the stop so the
         *     map stays correct after corrections.
         */
        patch: operations["patch_draft_stop_tours__tour_id__draft_stops__stop_id__patch"];
        trace?: never;
    };
    "/tours/{tour_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stops
         * @description Committed stops with address, task labels, and geocoded coordinate.
         *
         *     Returns every stop of the tour (including ungeocoded/unassigned ones, whose
         *     lat/lng are null) in the tour plan's original row order. Powers the mobile
         *     Review (edit hours) and Map (markers + detail) screens.
         */
        get: operations["list_stops_tours__tour_id__stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Tour
         * @description Confirm a tour and best-effort enrich stop opening hours from OSM.
         *
         *     Geocoding is assumed to have run already (stops carry a geom). Only stops
         *     whose hours are still unknown (hours_source='default') are looked up, so
         *     manual and previously-fetched OSM hours are never overwritten.
         */
        post: operations["commit_tour_tours__tour_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimise
         * @description Assign every confirmed market to a working day and order it.
         */
        post: operations["optimise_tours__tour_id__optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_stops__stop_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_tours_extract_post */
        Body_extract_tours_extract_post: {
            /** Image */
            image: string;
        };
        /** CommitResult */
        CommitResult: {
            /** Tour Id */
            tour_id: number;
            /** Status */
            status: string;
            /** Stops Total */
            stops_total: number;
            /** Stops Enriched */
            stops_enriched: number;
        };
        /** DayStop */
        DayStop: {
            /** Stop Id */
            stop_id: number;
            /** Sequence */
            sequence: number;
            /**
             * Eta
             * Format: time
             */
            eta: string;
        };
        /** DaySummary */
        DaySummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Stops */
            stops: components["schemas"]["DayStop"][];
            /** Drive Seconds */
            drive_seconds: number;
            /** Service Seconds */
            service_seconds: number;
            /** Day End */
            day_end: string | null;
            /** Near Limit */
            near_limit: boolean;
        };
        /** DraftStop */
        DraftStop: {
            /** Id */
            id: number;
            /** Street */
            street: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** City */
            city: string | null;
            /** Order No */
            order_no: string | null;
            /** Tasks */
            tasks: string | null;
            /** Remarks */
            remarks: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            /** Confidence */
            confidence: {
                [key: string]: number;
            };
        };
        /**
         * DraftStopUpdate
         * @description PATCH body for a draft stop — only explicitly-set fields are applied.
         *
         *     A field sent as ``null`` clears it; the endpoint distinguishes that from an
         *     omitted field via ``model_fields_set``.
         */
        DraftStopUpdate: {
            /** Street */
            street?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /** Order No */
            order_no?: string | null;
            /** Tasks */
            tasks?: string | null;
            /** Service Minutes */
            service_minutes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoursSource
         * @description Where a stop's opening/closing hours came from.
         * @enum {string}
         */
        HoursSource: "osm" | "manual" | "default";
        /** OptimiseResult */
        OptimiseResult: {
            /** Tour Id */
            tour_id: number;
            /** Days */
            days: components["schemas"]["DaySummary"][];
            /** Unassigned */
            unassigned: components["schemas"]["UnassignedStop"][];
        };
        /**
         * StopDetail
         * @description A committed stop with the address, task labels, and coordinate the map
         *     needs. lat/lng come from the PostGIS geom (null until geocoded); tasks is
         *     the stop's task labels joined for display.
         */
        StopDetail: {
            /** Id */
            id: number;
            /** Tour Id */
            tour_id: number;
            /** Customer */
            customer: string | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            hours_source: components["schemas"]["HoursSource"];
            /** Status */
            status: string;
            /** Street */
            street: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** City */
            city: string | null;
            /** Tasks */
            tasks: string | null;
            /** Remarks */
            remarks: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
        };
        /** StopRead */
        StopRead: {
            /** Id */
            id: number;
            /** Tour Id */
            tour_id: number;
            /** Customer */
            customer: string | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            hours_source: components["schemas"]["HoursSource"];
            /** Status */
            status: string;
        };
        /**
         * StopUpdate
         * @description Per-stop manual overrides. Only provided fields are applied (PATCH).
         */
        StopUpdate: {
            /** Opening Time */
            opening_time?: string | null;
            /** Closing Time */
            closing_time?: string | null;
            /** Service Minutes */
            service_minutes?: number | null;
        };
        /** TourDraft */
        TourDraft: {
            /** Tour Id */
            tour_id: number;
            /** Stops */
            stops: components["schemas"]["DraftStop"][];
        };
        /** UnassignedStop */
        UnassignedStop: {
            /** Stop Id */
            stop_id: number;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_tours_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_tours_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_tours__tour_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TourDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_draft_stop_tours__tour_id__draft_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftStopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftStop"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_tours__tour_id__stops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_tour_tours__tour_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimise_tours__tour_id__optimise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
