/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tours/{tour_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Tour
         * @description Confirm a tour and best-effort enrich stop opening hours from OSM.
         *
         *     Geocoding is assumed to have run already (stops carry a geom). Only stops
         *     whose hours are still unknown (hours_source='default') are looked up, so
         *     manual and previously-fetched OSM hours are never overwritten.
         */
        post: operations["commit_tour_tours__tour_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/{tour_id}/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimise
         * @description Assign every confirmed market to a working day and order it.
         */
        post: operations["optimise_tours__tour_id__optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_stops__stop_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommitResult */
        CommitResult: {
            /** Tour Id */
            tour_id: number;
            /** Status */
            status: string;
            /** Stops Total */
            stops_total: number;
            /** Stops Enriched */
            stops_enriched: number;
        };
        /** DayStop */
        DayStop: {
            /** Stop Id */
            stop_id: number;
            /** Sequence */
            sequence: number;
            /**
             * Eta
             * Format: time
             */
            eta: string;
        };
        /** DaySummary */
        DaySummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Stops */
            stops: components["schemas"]["DayStop"][];
            /** Drive Seconds */
            drive_seconds: number;
            /** Service Seconds */
            service_seconds: number;
            /** Day End */
            day_end: string | null;
            /** Near Limit */
            near_limit: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoursSource
         * @description Where a stop's opening/closing hours came from.
         * @enum {string}
         */
        HoursSource: "osm" | "manual" | "default";
        /** OptimiseResult */
        OptimiseResult: {
            /** Tour Id */
            tour_id: number;
            /** Days */
            days: components["schemas"]["DaySummary"][];
            /** Unassigned */
            unassigned: components["schemas"]["UnassignedStop"][];
        };
        /** StopRead */
        StopRead: {
            /** Id */
            id: number;
            /** Tour Id */
            tour_id: number;
            /** Customer */
            customer: string | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Service Minutes */
            service_minutes: number | null;
            hours_source: components["schemas"]["HoursSource"];
            /** Status */
            status: string;
        };
        /**
         * StopUpdate
         * @description Per-stop manual overrides. Only provided fields are applied (PATCH).
         */
        StopUpdate: {
            /** Opening Time */
            opening_time?: string | null;
            /** Closing Time */
            closing_time?: string | null;
            /** Service Minutes */
            service_minutes?: number | null;
        };
        /** UnassignedStop */
        UnassignedStop: {
            /** Stop Id */
            stop_id: number;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    commit_tour_tours__tour_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimise_tours__tour_id__optimise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tour_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
